```{r}
install.packages("nycflights13")
```
```{r}
library(nycflights13)
library(tidyverse)
```
```{r}
nycflights13::flights
```
```{r}
library(skimr)
```
```{r}
View(flights)
```
```{r}
skim_without_charts(nycflights13::flights)
```
```{r}
?nycflights13::flights
```
```{r}
flights %>%
  filter(arr_delay > 120)
```
```{r}
flights %>%
  filter(month == 1 & day == 1)
```
```{r}
flights %>%
  filter(month == 1 & day == 1)
```
```{r}
flights %>%
  filter(month %in% c(1, 2))
```
```{r}
primeiroTri <- flights %>%
  filter(month %in% c(1, 2, 3))
```
```{r}
primeiro_tri <- flights %>%
  filter(month == 1 | 2)

primeiro_tri
```
```{r}
flights %>%
  arrange(desc(dep_delay))
```
```{r}
flights %>%
  filter(dep_delay <= 10 & dep_delay >= -10) %>%
  arrange(desc(arr_delay))
```
```{r}
flights %>%
  distinct(origin, dest)
```
```{r}
flights %>%
  # unique()
  duplicated()
```
```{r}
flights %>%
  mutate(
    gain = dep_delay - arr_delay,
    speed = distance / air_time * 60,
    .before = 1
    # .after = day
  )
```
```{r}
flights %>%
  mutate(
    gain = dep_delay - arr_delay,
    hours = air_time / 60,
    gain_per_hour = gain / hours,
    .keep = "used"
    # .after = day
  )
```
```{r}
flights %>%
  select(year:day)
```
```{r}
flights %>%
  select(!year, day)
```
```{r}
primeiro_tri <- flights %>%
  select(num_range("month", 1:3))
primeiro_tri
```
```{r}
flights %>%
  relocate(year:dep_time,
    .after = time_hour
  )
```
```{r}
flights %>%
  relocate(arr_time,
    .before = dep_time
  )
```
```{r}
flights %>%
  relocate(starts_with("arr"), .before = dep_time)
```
```{r}
flights %>%
  group_by(month) %>%
  # filter(!is.na(sex))
  summarise(
    delay = mean(is.na(dep_delay)),
    n = n()
  )
```
```{r}
flights |>
  group_by(month) |>
  summarize(
    delay = mean(dep_delay, na.rm = TRUE),
    n = n()
  )
```
```{r}
flights |>
  group_by(dest) |>
  slice_max(arr_delay, n = 1) |>
 select(dest, arr_delay) |>
# select(dest, arr_delay) |>
# arrange(desc(dest, arr_delay))
```
```{r}
ggplot(
  data = flights, aes(y = dest, x = arr_delay)) +
  geom_bar(stat = "identity", fill = "#000000")

```
